export const SINOPSE = 'Sinopse';
export const INFO = 'Informações';
export const SITUATION = 'Situação';
export const LANGUAGE = 'Idioma';
export const BUDGET = 'Orçamento';
export const DURATION = 'Duração';
export const REVENUE = 'Receita';
export const PROFIT = 'Lucro';
export const NOT_OVERVIEW = 'Sem uma sinopse definida para esse filme';